Repository SENG-499-Company2-B01/Backend, pull requests merged in 2023-07, with the labels that each got.

#35 Updated Schedule Endpoints
  main.go
  modules/schedules/schedules.go
  mongodb/mongo-init.js
  mongodb/scripts/.env
  tests/main_test.go
Labels: enhancement

#36 GET and Post for past schedules
  main.go
  modules/middleware/middleware.go
Labels: new feature

#48 C2-66 Update Schedules Endpoints
  main.go
  modules/schedules/schedules.go
Labels: enhancement

#53 Add operation fixes for schedules endpoints
  main.go
  modules/schedules/schedules.go
  mongodb/scripts/db_seed.py
Labels: bug
