Repository SENG-499-Company2-B01/Backend, pull requests merged in 2023-06, with the labels that each got.

#14 C2-17 Moved router to main and grouped the endpoint.
  main.go
Labels: documentation

#13 C2-19 Creating a basic logging package
  go.mod
  go.sum
  logger/logger.go
  main.go
  tests/logger_test.go
Labels: enhancement

#17 C2-20 Logs write to mounted logs.txt file
  .gitignore
  Dockerfile
  docker-compose.yml
  logger/logger.go
  main.go
  modules/users/users.go
  tests/logger_test.go
Labels: enhancement

#21 C2-18 Update Readme
  LICENSE
  README.md
Labels: documentation

#23 C-22 Adding logs to basic module operations
  logger/logger.go
  modules/classrooms/classrooms.go
  modules/courses/courses.go
  modules/schedules/schedules.go
  modules/users/authentication.go
  modules/users/users.go
  tests/logger_test.go
Labels: enhancement

#25 C2 26 & C2 32 add verify jwt method and add role based access for users API
  main.go
  modules/helper/jwt.go
  modules/middleware/middleware.go
  modules/users/authentication.go
  modules/users/users.go
Labels: new feature

#32 Added logout endpoint and updated login to use username
  main.go
  modules/users/authentication.go
Labels: enhancement

#31 Setup and configure deployment
  .env
  .gitignore
  docker-compose.yml
  main.go
  modules/health/health.go
  mongodb/scripts/db_seed.py
  tests/main_test.go
Labels: enhancement
